Chore/initialize
js-soft/ts-serval pull request #1
Opened 2021-09-24 12:24 UTC by jkoenig134

2021-09-24 14:28 UTC, tnotheis requested changes

2021-09-24 14:28 UTC, tnotheis commented on tsconfig.test.json
> +        "strict": false, // Unfortunately strict mode has problems with decorators accessing the this context within getters/setters
Warum hast du den Kommentar entfernt? Würde entweder strict auf true setzen, oder, falls das nicht möglich ist, den Kommentar stehen lassen.

2021-09-24 18:41 UTC, jkoenig134 commented on tsconfig.test.json
> +        "strict": false, // Unfortunately strict mode has problems with decorators accessing the this context within getters/setters
Ich kann mich nicht daran erinnern das getan zu haben..? Ich mach ihn wieder rein

2021-09-27 06:16 UTC, tnotheis approved these changes

2021-09-27 06:19 UTC, merged